require File.dirname(__FILE__) + '/builder'
require File.dirname(__FILE__) + '/uploader'
require File.dirname(__FILE__) + '/project'
require File.dirname(__FILE__) + '/persistence'
require File.dirname(__FILE__) + '/workers/build_worker'
